 https://monex-ten.vercel.app/link/paint-dollar: https://t.me/+npFlOS8a1N4yMTdi
  https://monex-ten.vercel.app/link/paint-dollar-1: https://t.me/+BwUS5hyeAQ43MjQy
  https://monex-ten.vercel.app/link/usdt-cash: https://t.me/+AiYoGSQ9SgoyMzhi
  https://monex-ten.vercel.app/link/100k-usdt: https://t.me/+TM0vFFeda2UzODBi
  https://monex-ten.vercel.app/link/usdt-15min: https://t.me/+TTN33-pRc8gwZTli
  https://monex-ten.vercel.app/link/favorable-rate: https://t.me/+GINs5NLxXFQxZmNi
  https://monex-ten.vercel.app/link/crypto-1click: https://t.me/+y_dDG64KjVdlN2Qy
  https://monex-ten.vercel.app/link/here-now: https://t.me/+mfTh7BBzvDxhZTdi
  https://monex-ten.vercel.app/link/success-99: https://t.me/+1EnZwiuU1AtiZWMy
  https://monex-ten.vercel.app/link/no-surprises: https://t.me/+lymjXgizaZZkMmEy
  https://monex-ten.vercel.app/link/real-deals: https://t.me/+R5Y130nja7diYWQy
  https://monex-ten.vercel.app/link/p2p-vs-monex: https://t.me/+j3OaFjtE2yA1ZWRi
  https://monex-ten.vercel.app/link/money-in-hand: https://t.me/+tcm4dXruVrsyZDBi